name: latitude_and_longitude_converter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^5.0.0
  http: ^1.2.2
  google_maps_flutter: 2.10.0
  latlong2: 0.9.1
  connectivity: ^3.0.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
